package com.cqrs.cqrs;

public enum CommandType {
    CREATE_ORDER, ADD_FILM_TO_ORDER, PLACE_ORDER, RETURN_ORDER, CONFIRM_ORDER, CANCEL_ORDER,

    CREATE_CUSTOMER, CUSTOMER_PROCESS_ORDER,

    PROCESS_RETURN_LATE, CREATE_FILM
}
