package com.cqrs.cqrs;

public enum EventType {
    ADDED_TO_ORDER, ORDER_CREATED, ORDER_PLACED, ORDER_CONFIRMED, ORDER_RETURNED, ORDER_CANCELLED,
    CUSTOMER_CREATED, CUSTOMER_DEBITED, CUSTOMER_BALANCE_EXCEEDED, CUSTOMER_CONFIRMED_ORDER, CUSTOMER_BONUS_UPDATED,
    FILM_CREATED, ORDER_RETURNED_LATE;
}
